### PR TITLE
Bump version to v0.1.1

### PR DESCRIPTION
**Pull request by IanVaughan**

### CODE REVIEW

**Review by luizvarela — APPROVED** [review]

**Comment by stephenmoloney** [comment]
looks fine. The only thing I would add is that `iex fix` might not be something expected by a developer - ie that the test config is the default dev config.

**Comment by IanVaughan** [comment]
@stephenmoloney yeah, test should have its own config ideally, but it does no harm them being the same.

**Comment by stephenmoloney** [comment]
@IanVaughan Yea, I can't really think of a decent alternative right now so it's probably better that it doesn't crash as you say. If I think of a better solution, I'll make a PR.

Thanks.

:+1:  release 0.1.1

**Comment by IanVaughan** [comment]
@stephenmoloney are you able to Approve the PR?

**Comment by stephenmoloney** [comment]
@IanVaughan, just saw this today - I'm not able to approve.

**Pull request merged**
